
def get_story_names(subject: str = "UTS01", train_or_test="train"):
    TRAIN_STORIES_01 = ['adollshouse', 'adventuresinsayingyes', 'afatherscover', 'againstthewind', 'alternateithicatom', 'avatar', 'backsideofthestorm', 'becomingindian', 'beneaththemushroomcloud', 'birthofanation', 'bluehope', 'breakingupintheageofgoogle', 'buck', 'canadageeseandddp', 'canplanetearthfeedtenbillionpeoplepart1', 'canplanetearthfeedtenbillionpeoplepart2', 'canplanetearthfeedtenbillionpeoplepart3', 'catfishingstrangerstofindmyself', 'cautioneating', 'christmas1940', 'cocoonoflove', 'comingofageondeathrow', 'exorcism', 'eyespy', 'firetestforlove', 'food', 'forgettingfear', 'gangstersandcookies', 'goingthelibertyway', 'goldiethegoldfish', 'golfclubbing', 'googlingstrangersandkentuckybluegrass', 'gpsformylostidentity', 'hangtime', 'haveyoumethimyet', 'howtodraw', 'ifthishaircouldtalk', 'igrewupinthewestborobaptistchurch', 'inamoment', 'indianapolis', 'itsabox', 'jugglingandjesus', 'kiksuya', 'lawsthatchokecreativity', 'learninghumanityfromdogs',
                        'leavingbaghdad', 'legacy', 'life', 'lifeanddeathontheoregontrail', 'lifereimagined', 'listo', 'mayorofthefreaks', 'metsmagic', 'mybackseatviewofagreatromance', 'myfathershands', 'naked', 'notontheusualtour', 'odetostepfather', 'penpal', 'quietfire', 'reachingoutbetweenthebars', 'seedpotatoesofleningrad', 'shoppinginchina', 'singlewomanseekingmanwich', 'sloth', 'souls', 'stagefright', 'stumblinginthedark', 'superheroesjustforeachother', 'sweetaspie', 'swimmingwithastronauts', 'tetris', 'thatthingonmyarm', 'theadvancedbeginner', 'theclosetthatateeverything', 'thecurse', 'thefreedomridersandme', 'theinterview', 'thepostmanalwayscalls', 'theshower', 'thesurprisingthingilearnedsailingsoloaroundtheworld', 'thetiniestbouquet', 'thetriangleshirtwaistconnection', 'threemonths', 'thumbsup', 'tildeath', 'treasureisland', 'undertheinfluence', 'vixenandtheussr', 'waitingtogo', 'whenmothersbullyback', 'whyimustspeakoutaboutclimatechange', 'wildwomenanddancingqueens']
    TRAIN_STORIES_02_03 = ['adollshouse', 'adventuresinsayingyes', 'afatherscover', 'afearstrippedbare', 'againstthewind', 'alternateithicatom', 'avatar', 'backsideofthestorm', 'becomingindian', 'beneaththemushroomcloud', 'birthofanation', 'bluehope', 'breakingupintheageofgoogle', 'buck', 'canadageeseandddp', 'canplanetearthfeedtenbillionpeoplepart1', 'canplanetearthfeedtenbillionpeoplepart2', 'canplanetearthfeedtenbillionpeoplepart3', 'catfishingstrangerstofindmyself', 'cautioneating', 'christmas1940', 'cocoonoflove', 'comingofageondeathrow', 'escapingfromadirediagnosis', 'exorcism', 'eyespy', 'findingmyownrescuer', 'firetestforlove', 'food', 'forgettingfear', 'gangstersandcookies', 'goingthelibertyway', 'goldiethegoldfish', 'golfclubbing', 'googlingstrangersandkentuckybluegrass', 'gpsformylostidentity', 'hangtime', 'haveyoumethimyet', 'howtodraw', 'ifthishaircouldtalk', 'igrewupinthewestborobaptistchurch', 'inamoment', 'indianapolis', 'itsabox', 'jugglingandjesus', 'kiksuya', 'lawsthatchokecreativity', 'learninghumanityfromdogs',
                           'leavingbaghdad', 'legacy', 'life', 'lifeanddeathontheoregontrail', 'lifereimagined', 'listo', 'marryamanwholoveshismother', 'mayorofthefreaks', 'metsmagic', 'mybackseatviewofagreatromance', 'myfathershands', 'naked', 'notontheusualtour', 'odetostepfather', 'penpal', 'quietfire', 'reachingoutbetweenthebars', 'seedpotatoesofleningrad', 'shoppinginchina', 'singlewomanseekingmanwich', 'sloth', 'souls', 'stagefright', 'stumblinginthedark', 'superheroesjustforeachother', 'sweetaspie', 'swimmingwithastronauts', 'tetris', 'thatthingonmyarm', 'theadvancedbeginner', 'theclosetthatateeverything', 'thecurse', 'thefreedomridersandme', 'theinterview', 'thepostmanalwayscalls', 'thesecrettomarriage', 'theshower', 'thesurprisingthingilearnedsailingsoloaroundtheworld', 'thetiniestbouquet', 'thetriangleshirtwaistconnection', 'threemonths', 'thumbsup', 'tildeath', 'treasureisland', 'undertheinfluence', 'vixenandtheussr', 'waitingtogo', 'whenmothersbullyback', 'whyimustspeakoutaboutclimatechange', 'wildwomenanddancingqueens']
    TEST_STORIES = ["wheretheressmoke",
                    "onapproachtopluto", "fromboyhoodtofatherhood"]
    story_names_train = {
        "UTS01": TRAIN_STORIES_01,
        "UTS02": TRAIN_STORIES_02_03,
        "UTS03": TRAIN_STORIES_02_03,
    }
    if train_or_test == "train":
        return story_names_train[subject]
    elif train_or_test == "test":
        return TEST_STORIES
